name: Bug Report
description: File a bug report.
labels: ["bug"]
title: "🐞 - "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: replication
    attributes:
      label: Replication Steps
      description: Provide clear steps as to how this happened
      value: "1. First click this \n2. Navigate to this \n3. Click this \n4. See this"
    validations:
      required: false
  - type: dropdown
    id: kind
    attributes:
      label: Self hosted or Cloud?
      description: Does this happen on app.unsend.dev or on your own instance?
      options:
        - Cloud
        - Self hosted
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome (or chrome based like Brave, Arc, etc)
        - Safari